enum animenum
{
	UG_AnimName[40],
	UG_AnimCMD[40],
	UG_AnimDescription[64],
	UG_AnimCategory[32]
};
new UGMP_Anims[][animenum]=
{
	{"360flip1",				"/360flip1",		"360 Degree Flip1", 					"Actions"},
	{"360flip2",				"/360flip2",		"360 Degree Flip2", 					"Actions"},
	{"adance1",					"/adance1",			"A dance.", 							"Dances"},
	{"adance10",				"/adance10",		"A dance.", 							"Dances"},
	{"adance11",				"/adance11",		"A dance.", 							"Dances"},
	{"adance12",				"/adance12",		"A dance.", 							"Dances"},
	{"adance13",				"/adance13",		"A dance.", 							"Dances"},
	{"adance14",				"/adance14",		"A dance.", 							"Dances"},
	{"adance15",				"/adance15",		"A dance.", 							"Dances"},
	{"adance16",				"/adance16",		"A dance.", 							"Dances"},
	{"adance2",					"/adance2",			"A dance.", 							"Dances"},
	{"adance3",					"/adance3",			"A dance.", 							"Dances"},
	{"adance4",					"/adance4",			"A dance.", 							"Dances"},
	{"adance5",					"/adance5",			"A dance.", 							"Dances"},
	{"adance6",					"/adance6",			"A dance.", 							"Dances"},
	{"adance7",					"/adance7",			"A dance.", 							"Dances"},
	{"adance8",					"/adance8",			"A dance.", 							"Dances"},
	{"adance9",					"/adance9",			"A dance.", 							"Dances"},
	{"anotherdeath",			"/deathn",			"Another death animation.", 			"Actions"},
	{"armedchoppersit",			"/achopper",		"Idle machine gun animation.", 			"Idles"},
	{"armedidle",				"/aidle",			"Holding a gun by shoulder.", 			"Idles"},
	{"babyanim1",				"/babyanim1",		"Holding a baby.", 						"Idles"},
	{"babyanim2",				"/babyanim2",		"Alternative holding a baby.", 			"Idles"},
	{"backflip",				"/backflip",		"A back flip.", 						"Actions"},
	{"backflip720",				"/backflip720",		"A 720 back flip.", 					"Actions"},
	{"backflipsimple",			"/backflips",		"A simple backflip.", 					"Actions"},
	{"beachselfie",				"/beachselfie",		"A beach selfie.", 						"Idles"},
	{"biketrick1",				"/biketrick1",		"A bike trick.", 						"Actions"},
	{"biketrick2",				"/biketrick2",		"A bike trick.", 						"Actions"},
	{"biketrick3",				"/biketrick3",		"A bike trick.", 						"Actions"},
	{"biketrick4",				"/biketrick4",		"A bike trick.", 						"Actions"},
	{"bleeding_holder",			"/bleedh",			"Bleeding holder anim.", 				"Actions"},
	{"bleeding_injured",		"/bleedi",			"Bleeding animation.", 					"Actions"},
	{"bmxtrick1",				"/bmxtrick1",		"A bmx trick.", 						"Actions"},
	{"bmxtrick2",				"/bmxtrick2",		"A bmx trick.", 						"Actions"},
	{"bong",					"/bong",			"A hit from a bong anim.", 				"Actions"},
	{"breakdance",				"/breakdance",		"Break dancing.", 						"Dances"},
	{"burningdeath",			"/burndie",			"Burning death anim.", 					"Actions"},
	{"carcrash_nskill",			"/ccskill",			"Car crash anim.", 						"Actions"},
	{"carcrash_pass",			"/ccpass",			"Car Crash Pass",	 					"Actions"},
	{"carcrash_skilled",		"/ccskill2",		"Skilled car crash anim.", 				"Actions"},
	{"carhoodsit",				"/chsit",			"Sitting on a hood of a car.", 			"Idles"},
	{"carhoodsit2",				"/chsit2",			"Alt sitting on a hood of a car.", 		"Idles"},
	{"carhook1",				"/carhook1",		"Prostitute animation in a car.", 		"Actions"},
	{"carhook2",				"/carhook2",		"Hooker in Car 1",	 					"Actions"},
	{"carhook3",				"/carhook3",		"Hooker in Car 2", 						"Actions"},
	{"carrycorpse_player",		"/ccorpsep",		"Carrying a player's corpse.", 			"Actions"},
	{"clappinghands",			"/claphand",		"A hand clapping anim.", 				"Actions"},
	{"comeatme",				"/comeatme",		"Signal to come.", 						"Idles"},
	{"continueflip",			"/cflip",			"Continuing Flip", 						"Actions"},
	{"cop_aimgun",				"/copaim",			"A cop aiming a gun.", 					"Idles"},
	{"cop_holdgun",				"/cophold",			"Cop holding belt animation.", 			"Idles"},
	{"copcrossarms",			"/copcross",		"Cop crossing his arms.", 				"Idles"},
	{"couchidle",				"/couchh",			"Sitting on a couch idle.", 			"Idles"},
	{"cover1",					"/cover1",			"Cover anim.", 							"Idles"},
	{"cover2",					"/cover2",			"Cover anim.", 							"Idles"},
	{"cover3",					"/cover3",			"Cover anim.", 							"Idles"},
	{"cover4",					"/cover4",			"Cover anim.", 							"Idles"},
	{"cover5",					"/cover5",			"Cover anim.", 							"Idles"},
	{"crossarmseat",			"/crossaseat",		"Sitting in a cross arm position.", 	"Idles"},
	{"cs_aim",					"/csaim",			"Aiming animation.", 					"Cutscene, Actions"},
	{"cs_aiminghandgun",		"/csaimgun",		"Handgun aiming.", 						"Cutscene, Actions"},
	{"cs_aimingrifle",			"/csaimrifle",		"Rifle aiming.", 						"Cutscene, Actions"},
	{"cs_alerted",				"/csalerted",		"Alerted anim.", 						"Cutscene, Actions"},
	{"cs_angryphonecall",		"/csangrypcall",	"Angry phone call anim.", 				"Cutscene, Actions"},
	{"cs_angryphonecall2",		"/csangrypcall2",	"Alternative angry phonecall.", 		"Cutscene, Actions"},
	{"cs_benchsit",				"/csbenchsit",		"Sitting on a bench.", 					"Cutscene, Idles"},
	{"cs_bleeding",				"/csbleeding",		"Bleeding animation.", 					"Cutscene, Actions"},
	{"cs_boxpractice",			"/csboxpractice",	"Boxing practice.", 					"Cutscene, Actions"},
	{"cs_cocainesnort",			"/cscocainesnort",	"Snorting coke.", 						"Cutscene, Actions"},
	{"cs_dancebeat",			"/csdancebeat",		"Beat dancing.", 						"Cutscene, Dances"},
	{"cs_dancehiphop",			"/csdancehiphop",	"Hip hop dancing.", 					"Cutscene, Dances"},
	{"cs_desksit",				"/csdesksit",		"Desk sit anim.", 						"Cutscene"},
	{"cs_djdance",				"/csdjdance",		"DJ dancing.", 							"Cutscene, Dances"},
	{"cs_djrecorddance",		"/csdjrdance",		"A DJ dance.", 							"Cutscene, Dances"},
	{"cs_dontleave",			"/csdleave",		"Signalling not to leave.", 			"Cutscene"},
	{"cs_eatfood",				"/cseatfood",		"Food eating anim.", 					"Cutscene, Actions"},
	{"cs_femmiedance",			"/csfemdance",		"A female dance.", 						"Cutscene, Dances"},
	{"cs_gangchat",				"/csgang",			"Gang style talk.", 					"Cutscene"},
	{"cs_getout",				"/csgetout",		"Get Out",			 					"Cutscene, Actions"},
	{"cs_getup",				"/csgetup",			"Get Up", 								"Cutscene, Actions"},
	{"cs_guncheck",				"/csguncheck",		"Gun check.", 							"Cutscene, Actions"},
	{"cs_guncheck2",			"/csguncheck2",		"Alternative gun check.", 				"Cutscene, Actions"},
	{"cs_handsuprelax",			"/cshandsuprelax",	"Relaxed hands up.", 					"Cutscene, Actions"},
	{"cs_idletablechat",		"/csidletablechat",	"Idle Tablet Chat", 					"Cutscene, Actions"},
	{"cs_injured",				"/csinjured",		"Injured anim.", 						"Cutscene, Actions"},
	{"cs_interrogation",		"/csinterrogation",	"Interrogation animation.", 			"Cutscene, Actions"},
	{"cs_japchick",				"/csjapchick",		"Jap a chick", 							"Cutscene"},
	{"cs_jazzdance",			"/csjazzdance",		"A funky dance.", 						"Cutscene, Dances"},
	{"cs_jazzdance2",			"/csjazzdance2",	"Alternative funky dance.", 			"Cutscene, Dances"},
	{"cs_laugh",				"/cslaugh",			"Laughing anim.", 						"Cutscene, Actions"},
	{"cs_meditate",				"/csmeditate",		"Mediate.",			 					"Cutscene, Actions"},
	{"cs_oldrelax",				"/csoldrelax",		"Old person relaxing.", 				"Cutscene, Actions"},
	{"cs_partyhard",			"/cspartyhard",		"Party dancing.", 						"Cutscene, Dances"},
	{"cs_phonecall",			"/csphonecall",		"Phone Call",		 					"Cutscene, Actions"},
	{"cs_poledance",			"/cspoledance",		"A stripper pole dance.", 				"Cutscene, Dances"},
	{"cs_popdance",				"/cspopdance",		"Pop dancing.", 						"Cutscene, Dances"},
	{"cs_popdance2",			"/cspopdance2",		"Pop dancing.", 						"Cutscene, Dances"},
	{"cs_relaxbenchtalk",		"/csbenchtalk",		"A relaxed sitting talking anim.", 		"Cutscene, Actions"},
	{"cs_relaxedidlesit",		"/csidlesit",		"Relaxed sitting.", 					"Cutscene, Idles"},
	{"cs_relaxedidlesit2",		"/csidlesit2",		"Alternative relaxed anim.", 			"Cutscene, Idles"},
	{"cs_relaxntalk",			"/cstalk",			"Relaxing and talking.", 				"Cutscene, Actions"},
	{"cs_relaxsit",				"/cssit",			"Relaxed sitting.", 					"Cutscene, Actions"},
	{"cs_relaxtable",			"/cstable",			"Relaxing at a table.", 				"Cutscene, Idles"},
	{"cs_relaxwalkt",			"/cswalkt",			"Relaxed walk.", 						"Cutscene, Actions"},
	{"cs_repairing",			"/csrepair",		"Reparing animation.", 					"Cutscene, Actions"},
	{"cs_riptenpenny",			"/csriptenpenny",	"Tenpenny death anim.", 				"Cutscene, Actions"},
	{"cs_robodance",			"/csrobodance",		"Robo style dancing.", 					"Cutscene, Dances"},
	{"cs_sadsitchat",			"/cssadsitchat",	"A sad sitting talking anim.", 			"Cutscene, Actions"},
	{"cs_serioustalking",		"/cssertalk",		"Talking in a serious manner.", 		"Cutscene, Actions"},
	{"cs_sitchat",				"/csschat",			"Sitting and talking.", 				"Cutscene, Actions"},
	{"cs_sitchat",				"/csschat1",		"Sitting and chatting.", 				"Cutscene, Actions"},
	{"cs_sitdiscuss",			"/cssdiscuss",		"Sitting and talking.", 				"Cutscene, Actions"},
	{"cs_sittalk",				"/csstalk",			"Sitting and talking.", 				"Cutscene, Actions"},
	{"cs_sitwidechat",			"/csswidechat",		"Wide chair sitting and chatting.", 	"Cutscene, Actions"},
	{"cs_sneakpeak",			"/cssneakpeak",		"Sneak Peak",		 					"Cutscene"},
	{"cs_standcchat",			"/csstandcchat",	"Standing up and talking.", 			"Cutscene, Actions"},
	{"cs_stresssittalk",		"/cssttalk",		"Stressful talking.", 					"Cutscene, Actions"},
	{"cs_talk",					"/cstalk2",			"Talking animation", 					"Cutscene, Actions"},
	{"cs_talkingtoinjured",		"/cstalkinj",		"Talking to injured person.", 			"Cutscene, Actions"},
	{"cs_tasktalk",				"/cstasktalk",		"Talking animation.", 					"Cutscene, Actions"},
	{"cs_tieknee",				"/csknee",			"Tie Knee",			 					"Cutscene, Actions"},
	{"cs_tiesit",				"/cssit2",			"Sitting animation.", 					"Cutscene, Actions"},
	{"cs_timetomeditate",		"/csmeditate1",		"Meditation anim.", 					"Cutscene, Actions"},
	{"cs_timetotalk",			"/csttt",			"Time To Talk.",	 					"Cutscene, Actions"},
	{"cs_videogame",			"/csvideogame",		"Video game anim.", 					"Cutscene, Actions"},
	{"cs_warmup",				"/cswarmup",		"Warm Up",			 					"Cutscene, Actions"},
	{"cs_whack",				"/cswhack",			"Whack animation.", 					"Cutscene, Actions"},
	{"cs_yogi2",				"/csyogi2",			"Yoga anim.", 							"Cutscene, Actions"},
	{"csinspectwep",			"/csinspectwep",	"Inspect a weapon", 					"Cutscene, Actions"},
	{"cutesit",					"/cutesit",			"A sitting animation.", 				"Idles"},
	{"dab",						"/dab2",			"A dab.", 								"Actions"},
	{"deadnewidle",				"/deadnewidle",		"Lying on the floor animation.", 		"Idles"},
	{"deathback",				"/deathback",		"Death from the back.", 				"Actions"},
	{"deathfall",				"/deathfall",		"A falling death animation.", 			"Actions"},
	{"deathfront",				"/deathfront",		"Death from the front.", 				"Actions"},
	{"deathspin",				"/deathspin",		"A spinning death anim.", 				"Actions"},
	{"decentfuckyou",			"/decentfuckyou",	"Decent signal of displeasure.", 		"Actions"},
	{"downbegger",				"/downbegger",		"Begging anim.", 						"Actions"},
	{"drillmove",				"/drillmove",		"A drill acrobatic manuever.", 			"Actions"},
	{"dropcorpse_player",		"/dcorpsep",		"Dropping a player's corpse.", 			"Actions"},
	{"emptycash",				"/emptycash",		"Emptying a cash register.", 			"Actions"},
	{"femmie_gunwk",			"/fgunwk",			"Female gun walk anim.", 				"Actions"},
	{"femmie_gunwk2",			"/fgunwk2",			"Alt female gun walk anim.", 			"Actions"},
	{"femmie_idle1",			"/fidle1",			"Idle female anim.", 					"Idles"},
	{"femmie_idle2",			"/fidle2",			"Alternative female idle anim.", 		"Idles"},
	{"femmie_idlestance",		"/fidlestance",		"Female idle.", 						"Idles"},
	{"femmie_naughty",			"/fnaughty",		"Naughty Female",	 					"Actions"},
	{"femmie_playerwk",			"/fplayerwk",		"Female player walking anim.", 			"Actions"},
	{"femmie_pose",				"/fpose",			"Female pose.", 						"Idles"},
	{"femmie_pose2",			"/fpose2",			"Female posing.", 						"Idles"},
	{"femmie_pose3",			"/fpose3",			"Female posing.", 						"Idles"},
	{"femmie_pose4",			"/fpose4",			"Female pose.", 						"Idles"},
	{"femmie_pose5",			"/fpose5",			"Female pose.", 						"Idles"},
	{"femmie_pose6",			"/fpose6",			"A female pose.", 						"Idles"},
	{"femmie_pose7",			"/fpose7",			"Female posing.", 						"Idles"},
	{"femmie_pose8",			"/fpose8",			"Female posing.", 						"Idles"},
	{"femmie_pose9",			"/fpose9",			"Female posing.", 						"Idles"},
	{"femmie_sit",				"/fsit",			"A female sit anim.", 					"Actions"},
	{"femmie_sit2",				"/fsit2",			"Female sitting.", 						"Idles"},
	{"femmie_sit3",				"/fsit3",			"Female sitting.", 						"Idles"},
	{"femmie_sit4",				"/fsit4",			"Female sitting.", 						"Idles"},
	{"femmie_sit5",				"/fsit5",			"Female sitting.", 						"Idles"},
	{"femmie_wepcr",			"/fwepcr",			"Crouch animation.", 					"Actions"},
	{"femmie_wkperiod",			"/fwkperiod",		"Old walk animation.", 					"Actions"},
	{"femmierelaxed",			"/frelaxed",		"Female Relaxed.",	 					"Idles"},
	{"fish_idle",				"/fishidle",		"Fishing idle animation.", 				"Actions"},
	{"fish_pull",				"/fishpull",		"Fishing pull animation.", 				"Actions"},
	{"fish_struggle",			"/fishstruggle",	"Fishing struggle.", 					"Actions"},
	{"fish_toss",				"/fishtoss",		"Fishing toss anim.", 					"Actions"},
	{"fishingidle",				"/fishingidle",		"A fishing idle animation.", 			"Idles"},
	{"freewayidle",				"/freewayidle",		"Freeway bike idle.", 					"Idles"},
	{"freewayidle2",			"/freewayidle2",	"Freeway bike idle.", 					"Idles"},
	{"freewayidle3",			"/freewayidle3",	"Freeway bike idle.", 					"Idles"},
	{"freewayidle4",			"/freewayidle4",	"Freeway bike idle.", 					"Idles"},
	{"fuckoffpal",				"/fuckoffpal",		"A gesture to signal displeasure.", 	"Actions"},
	{"gearshift",				"/gearshift",		"Gear shifting in a car.", 				"Actions"},
	{"glider_hang",				"/gliderhang",		"Glider hanging.", 						"Actions"},
	{"glider_loop",				"/gliderloop",		"Glider loop.", 						"Actions"},
	{"golf_high",				"/golfhigh",		"Strong golf anim.", 					"Actions"},
	{"golf_low",				"/golflow",			"Low gold anim.", 						"Actions"},
	{"golf_med",				"/golfmed",			"Medium golf anim.", 					"Actions"},
	{"gs1",						"/gs1",				"Gang sign.", 							"Actions"},
	{"gs2",						"/gs2",				"Gang sign.", 							"Actions"},
	{"gs3",						"/gs3",				"Gang sign.", 							"Actions"},
	{"gs4",						"/gs4",				"Gang sign.", 							"Actions"},
	{"gs5",						"/gs5",				"Gang sign.", 							"Actions"},
	{"gs6",						"/gs6",				"Gang sign.", 							"Actions"},
	{"gs7",						"/gs7",				"Gang sign.", 							"Actions"},
	{"gs8",						"/gs8",				"Gang sign.", 							"Actions"},
	{"gs9",						"/gs9",				"Gang sign.", 							"Actions"},
	{"guitar_classical",		"/gtcl",			"Guitar animation.", 					"Actions"},
	{"guitar_rock",				"/gtrk",			"Guitar animation.", 					"Actions"},
	{"gunaim",					"/gunaim",			"Aiming gun.", 							"Actions"},
	{"gunwalk",					"/gunwalk",			"Walking with a gun.", 					"Actions"},
	{"handaccuracy",			"/haccu",			"Acrobatic handstand.", 				"Actions"},
	{"handbreaking",			"/hbreak",			"Arm break animation.", 				"Actions"},
	{"handsbehindurback",		"/hbehind",			"Hands behind back.", 					"Actions"},
	{"handsnair",				"/handair",			"Hands in the air.", 					"Actions"},
	{"handsonpistol",			"/handpistol",		"Hands on a pistol.", 					"Idles"},
	{"handstand",				"/hstand",			"A hand stand.", 						"Actions"},
	{"handstand2",				"/hstand1",			"Alternative hand stand.", 				"Actions"},
	{"handstand3",				"/hstand2",			"Alternative hand stand.", 				"Actions"},
	{"handstand3finish",		"/hstand3",			"Hand stand finish.", 					"Actions"},
	{"handstandyogis",			"/hstand4",			"Hand stand yoga style.", 				"Actions"},
	{"handsupback",				"/handsupb",		"Hands behind back.", 					"Actions"},
	{"handsupdairboi",			"/handsupa",		"Hastly hands up in the air.", 			"Actions"},
	{"handsuponknee",			"/handsupk",		"Hands behind head on knees.", 			"Actions"},
	{"handsuponknee_idle",		"/handsupki",		"Idle on knees.", 						"Actions"},
	{"handsuponknee_stand",		"/handsupst",		"Standing hands behind head.", 			"Actions"},
	{"hangingup",				"/hanghook",		"Hanging from a hook.", 				"Idles"},
	{"hip_idle",				"/hidle",			"A hip idle anim.", 					"Idles"},
	{"hip_walk",				"/hwalk",			"Hip walking style.", 					"Actions"},
	{"holder_aimathostage",		"/aimho",			"Holder aiming at the hostage.", 		"Actions"},
	{"holder_aimforward",		"/aimfo",			"Holder aiming forward.", 				"Actions"},
	{"holder_holdmouth",		"/holdm",			"Holder holding hostage's mouth.", 		"Actions"},
	{"holder_idle",				"/holds",			"Hostage holder idle animation.", 		"Actions"},
	{"holder_struggle",			"/holdstr",			"Hostage holder stuggling.", 			"Actions"},
	{"holdonthewall",			"/hotw",			"Acrobatic flag manuever.", 			"Actions"},
	{"holyshitbackflip",		"/holyshit",		"An impressive backflip.", 				"Actions"},
	{"hostage_idle",			"/hoidle",			"Hostage idle animation.", 				"Actions"},
	{"hostage_struggle",		"/hostrg",			"Hostage struggling.", 					"Actions"},
	{"idle_assault",			"/idass",			"Idle with assault rifle.", 			"Idles"},
	{"idle_wheavy",				"/idwh",			"Idle with a heavy weapon.", 			"Idles"},
	{"idle_wphone",				"/idwp",			"Idle with a phone.", 					"Idles"},
	{"idle_wrifle",				"/idwr",			"Idle with rifle.", 					"Idles"},
	{"idle_wsheavy",			"/idws",			"Idle with heavy gun.", 				"Idles"},
	{"idlehandback",			"/handback",		"Idle hands behind back.", 				"Idles"},
	{"item_deposit",			"/itemdep",			"Item Deposit.",	 					"Actions"},
	{"item_holdncheck",			"/hitemch",			"Holding and checking an item.", 		"Actions"},
	{"kickedupfeetcigar",		"/kickupcig",		"Feet up with a cigar.", 				"Idles"},
	{"kickurfootup",			"/kickfoot",		"Sitting while feet up.", 				"Idles"},
	{"knockedout",				"/knocked",			"Knocked out animation.", 				"Idles"},
	{"ladder_longdown",			"/lldown",			"Ladder animation.", 					"Actions"},
	{"ladder_longup",			"/llup",			"Ladder animation.", 					"Actions"},
	{"ladder_shortdown",		"/lsdown",			"Ladder animation.", 					"Actions"},
	{"ladder_shortup",			"/lsup",			"Ladder animation.", 					"Actions"},
	{"leanonobj",				"/leanobj",			"Leaning animation.", 					"Idles"},
	{"longdab",					"/dab",				"A long dab gesture.", 					"Actions"},
	{"lookalive",				"/lalive",			"A familiar dance animation.", 			"Actions"},
	{"marryme",					"/marryme",			"A kneeling marry me position.", 		"Actions"},
	{"mirrorselfie",			"/mselfie",			"Mirror Selfie1", 						"Idles"},
	{"mirrorselfie2",			"/mselfie1",		"Mirror Selfie2", 						"Idles"},
	{"mirrorselfie3",			"/mselfie2",		"Mirror Selfie3", 						"Idles"},
	{"mirrorselfie4",			"/mselfie3",		"Mirror Selfie4", 						"Idles"},
	{"MisterVercetti",			"/mverc",			"Tommy's slow walk anim.", 				"Actions"},
	{"moonwalkmj",				"/mjmw",			"MJ's moonwalk dance.", 				"Dances"},
	{"mopfloor",				"/mopf",			"Mopping floor animation.", 			"Actions"},
	{"nazisalute",				"/nazi",			"A nazi salute.", 						"Actions"},
	{"newchairsit",				"/chsit3",			"Sitting on a chair.", 					"Actions"},
	{"newgwalk1",				"/ngwalk",			"Alt gangster walking style.", 			"Actions"},
	{"newgwalk2",				"/ngwalk1",			"New gangster walking style.", 			"Actions"},
	{"niggaogloc",				"/nigga",			"OG Loc's rapping animation.", 			"Dances"},
	{"nrgtrick1",				"/nrgtrick1",		"An nrg bike trick.", 					"Actions"},
	{"nrgtrick2",				"/nrgtrick2",		"An nrg bike trick.", 					"Actions"},
	{"nrgtrick3",				"/nrgtrick3",		"An nrg bike trick.", 					"Actions"},
	{"nrgtrick4",				"/nrgtrick4",		"An nrg bike trick.", 					"Actions"},
	{"onehandstandmad",			"/ohstand",			"A handstand on one hand.", 			"Actions"},
	{"oneloopflipper",			"/olflip",			"One Loop Flipper.", 					"Actions"},
	{"parkourfrontroll",		"/pfroll",			"Self Parkour Front Roll.", 			"Actions"},
	{"pickcorpse_player",		"/pcorpse",			"Picking up a player's corpse.", 		"Actions"},
	{"pkor1",					"/pkor1",			"Parkour anim.", 						"Actions"},
	{"pkor2",					"/pkor2",			"Parkour anim.", 						"Actions"},
	{"pkor3",					"/pkor3",			"Parkour anim.", 						"Actions"},
	{"pkor4",					"/pkor4",			"Parkour anim.", 						"Actions"},
	{"pkor5",					"/pkor5",			"Parkour anim.", 						"Actions"},
	{"pkor6",					"/pkor6",			"Parkour anim.", 						"Actions"},
	{"pkor7",					"/pkor7",			"Parkour anim.", 						"Actions"},
	{"praythelord",				"/praylord",		"Praying animation.", 					"Actions"},
	{"probackflipdance",		"/flipdance",		"A back flip dance.", 					"Actions"},
	{"psy",						"/psy",				"Psy's gangnam style dance.", 			"Dances"},
	{"relaxedidlesit",			"/rlxsit",			"Relaxed idle sitting.", 				"Idles"},
	{"relaxfemmie1",			"/rlxf1",			"alternative beach relaxing", 			"Idles"},
	{"relaxfemmie2",			"/rlxf2",			"Female beach relaxing.", 				"Idles"},
	{"relaxfemmie3",			"/rlxf3",			"female beach relaxing", 				"Idles"},
	{"relaxfemmie4",			"/rlxf4",			"Beach relaxing.", 						"Idles"},
	{"relaxfemmieshot",			"/rlxf5",			"female beach posing", 					"Idles"},
	{"relaxseat",				"/rlxseat",			"Relaxed seat.", 						"Idles"},
	{"rnddoublebackflip",		"/dbflip",			"Double backflip.", 					"Actions"},
	{"robocopdance",			"/robocop",			"Robo cop dance.", 						"Dances"},
	{"roundbabyround",			"/roundbb",			"Cartwheel and a bunch of flips.", 		"Actions"},
	{"roundblansh",				"/roundb",			"A front flip and a bunch of flips.", 	"Actions"},
	{"salute",					"/salute",			"An army salute.", 						"Actions"},
	{"selfie",					"/selfie",			"A selfie animation.", 					"Actions"},
	{"selfiewithbuddy",			"/selfie2",			"A selfie with a friend.", 				"Actions"},
	{"slapforehead",			"/slapfh",			"A forehead slap animation.", 			"Actions"},
	{"sneeze",					"/sneeze",			"Sneeze.",			 					"Actions"},
	{"softbackflip",			"/spdf",			"A backflip.", 							"Actions"},
	{"spindeathleft",			"/spdf1",			"Spinning death from the left.", 		"Actions"},
	{"spindeathright",			"/spdr",			"Spinning death from the right.", 		"Actions"},
	{"squat",					"/squat",			"Squat.",			 					"Idles"},
	{"squat2",					"/squat2",			"Squat2.",			 					"Idles"},
	{"starthandstand1",			"/sths",			"Start Hand Stand.", 					"Actions"},
	{"sweetparkoured",			"/swpar",			"Sweet Parkoured.", 					"Actions"},
	{"takeaphil",				"/tkap",			"Pill swallowing anim.", 				"Actions"},
	{"thumbsdown",				"/thdn",			"Thumbs down.", 						"Actions"},
	{"thumbsup",				"/thup",			"Thumbs up.", 							"Actions"},
	{"toss_money",				"/tossm",			"Toss Money.",		 					"Actions"},
	{"umbrella_idle",			"/umbw",			"Umbrella idle anim.", 					"Actions"},
	{"umbrella_idle2",			"/umbw1",			"Alternative umbrella idle anim.", 		"Actions"},
	{"umbrella_walk",			"/umbw2",			"Umbrella walking animation.", 			"Actions"},
	{"umbrella_walk2",			"/umbw3",			"Alternative umbrella walking.", 		"Actions"},
	{"upsidedownpush",			"/usdp",			"Upside Down Push.", 					"Actions"},
	{"vccivilwalk",				"/vccw",			"VC Civilian walking style.", 				"Actions"},
	{"vchairsit",				"/vchsit",			"Sitting on a chair.", 					"Idles"},
	{"virgindance",				"/vird",			"A familiar dance animation1.", 		"Dances"},
	{"virgindance10",			"/vird1",			"A familiar dance animation2.", 		"Dances"},
	{"virgindance11",			"/vird2",			"A familiar dance animation3.", 		"Dances"},
	{"virgindance12",			"/vird3",			"A familiar dance animation4.", 		"Dances"},
	{"virgindance2",			"/vird4",			"A familiar dance animation5.", 		"Dances"},
	{"virgindance3",			"/vird5",			"A familiar dance animation6.", 		"Dances"},
	{"virgindance4",			"/vird55",			"A familiar dance animation7.", 		"Dances"},
	{"virgindance5",			"/vird6",			"A familiar dance animation8.", 		"Dances"},
	{"virgindance6",			"/vird7",			"A familiar dance animation9.", 		"Dances"},
	{"virgindance7",			"/vird8",			"A familiar dance animation10.", 		"Dances"},
	{"virgindance8",			"/vird9",			"A familiar dance animation11.", 		"Dances"},
	{"virgindance9",			"/vird10",			"A familiar dance animation12.", 		"Dances"},
	{"walk_fatnold",			"/wfat",			"A fat and old walk anim.", 			"Actions"},
	{"walk_wsheavy",			"/wwsh",			"Walk with a heavy gun.", 				"Actions"},
	{"walkhandsback1",			"/whback1",			"Hands Back On Walk1.",					"Actions"},
	{"walkhandsback2",			"/whback2",			"Hands Back On Walk2.", 				"Actions"},
	{"walkhandsback3",			"/whback3",			"Hands Back On Walk3.", 				"Actions"},
	{"walktough",				"/wtou",			"Tough walking style.", 				"Actions"},
	{"wallbacklflip",			"/wbflip",			"A wall backflip.", 					"Actions"},
	{"wallflipparkour",			"/wfpar",			"Wall Flip Parkour.", 					"Actions"},
	{"wallfrontflip",			"/wfflip",			"A wall front flip.", 					"Actions"},
	{"wallsideflip",			"/wsflip",			"A wall side flip.", 					"Actions"},
	{"warmup2",					"/wup",				"Warm up.",			 					"Actions"},
	{"widechairsit",			"/widecs",			"Sitting on a wide chair.", 			"Actions"},
	{"zombie_eat",				"/ze",				"Zombie Eat.", 							"Actions"},
	{"zombie_idle",				"/zi",				"Zombie Idle.", 						"Actions"},
	{"zombie_run",				"/zr",				"Zombie Run1.", 						"Actions"},
	{"zombie_run2",				"/zr2",				"Zombie Run2.", 						"Actions"},
	{"zombie_walk",				"/zw1",				"Zombie Walk1.", 						"Actions"},
	{"zombie_walk2",			"/zw2",				"Zombie Walk2.", 						"Actions"},
	{"zombie_walk3",			"/zw3",				"Zombie Walk3.", 						"Actions"},
	{"zombie_walk4",			"/zw4",				"Zombie Walk4.", 						"Actions"},
	{"zombie_walk5",			"/zw5",				"Zombie Walk5.", 						"Actions"},
	{"zombie_walk6",			"/zw6",				"Zombie Walk6.", 						"Actions"},
	{"zombie_walk7",			"/zw7",				"Zombie Walk7.", 						"Actions"},
	{"zombie_walk8",			"/zw8",				"Zombie Walk8.", 						"Actions"}
};
